name: iboss
description: Business and Personal Financial Management

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.8+4
  fl_chart: ^0.63.0
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  animations: ^2.0.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#00BF63"
  image: assets/splash.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#00BF63"
  adaptive_icon_foreground: "assets/icon-android.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

