name: iboss
description: Business and Personal Financial Management

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+4

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.63.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.3.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  uuid: ^4.0.0
  rxdart: ^0.27.7
  image_picker: ^1.0.4

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#003060"
  image: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

